version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
artifacts:
- path: '**\*.nupkg'
  name: NuGet
before_build:
- cmd: >-
    nuget restore

    choco install opencover.portable

    choco install codecov
build:
  project: FluentValidation.Extensions.Br.sln
  publish_nuget: true
  verbosity: detailed
test_script:
- cmd: >-
    OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\test\FluentValidation.Extensions.Br.Test\bin\Debug\FluentValidation.Extensions.Br.Test.dll -noshadow" -output:".\covarge_report.xml"

    codecov -f "covarge_report.xml"
deploy:
- provider: NuGet
  api_key:
    secure: bYJGeNtU8mn1jyjM4ZXHyQdL9sBUt4NbmQoVQHTVDeEaj2AsafQWmySSwPKJXOhRvTmbmw2nn+woZMFK6GKxg+oJxO6f7X0fhjUxEmKyKoE=
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
