name: Commit Conventions Linter
description: Lints Pull Request commit messages with commitlint
author: Lucas Mendes Loureiro
inputs:
  token:
    description: >
      Personal access token (PAT) used to interact with the GitHub API. By default, the automatic
      token provided by GitHub is used. You can see more info about GitHub's default token here:
      https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
    default: ${{ github.token }}
    required: false
outputs:
  results:
    description: The error and warning messages of the analyzed commits
runs:
  using: "node12"
  main: "src/index.js"